---
services:
  pyroscope:
    container_name: pyroscope
    image: grafana/pyroscope:latest
    ports:
    - 4040:4040
    networks:
    - pyroscope
    volumes:
    - ./pyroscope_data:/data
  grafana:
    container_name: grafana
    image: grafana/grafana:main
    ports:
    - 3000:3000
    environment:
    - GF_FEATURE_TOGGLES_ENABLE=flameGraph
    networks:
    - pyroscope
    depends_on:
    - pyroscope
  paychecks:
    image: docker.io/visionir/paychecks:latest
    pull_policy: always
    ports:
    - 8501:8501
    networks:
    - pyroscope
networks:
  pyroscope:
    driver: bridge
