---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: double-quote-string-fixer
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.21.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.4
      hooks:
          - id: ruff
            types_or: [python, pyi, jupyter]
          - id: ruff-format
            types_or: [python, pyi, jupyter]
