# generated by datamodel-codegen:
#   filename:  user.json
#   timestamp: 2024-03-28T00:01:47+00:00

from datetime import datetime

from pydantic import BaseModel


class City(BaseModel):
    id: str
    name: str
    ascii_name: str
    state: str
    ascii_state: str
    country_code: str
    population: int
    timezone: str
    country: str
    title: str


class User(BaseModel):
    id: str
    email: str
    timezone: str
    timeout: int
    writes_only: bool
    created_at: datetime
    last_project: str
    linkedin_username: str
    is_hireable: bool
    last_branch: str | None
    color_scheme: str
    logged_time_public: bool
    time_format_24hr: bool
    is_email_confirmed: bool
    has_basic_features: bool
    public_email: str
    modified_at: datetime
    is_email_public: bool
    github_username: str
    last_plugin_name: str
    languages_used_public: bool
    display_name: str
    bio: str
    website: str
    invoice_id_format: str
    photo_public: bool
    meetings_over_coding: bool
    plan: str
    has_premium_features: bool
    show_machine_name_ip: bool
    weekday_start: int
    profile_url_escaped: str
    photo: str
    last_plugin: str
    city: City
    share_last_year_days: bool
    full_name: str
    date_format: str
    location: str | None
    human_readable_website: str
    last_heartbeat_at: datetime
    is_onboarding_finished: bool
    time_format_display: str
    share_all_time_badge: bool
    profile_url: str
    username: str
    needs_payment_method: bool
    twitter_username: str
    default_dashboard_range: str
    wonderfuldev_username: str | None
    public_profile_time_range: str
    durations_slice_by: str
