---
services:
  paychecks:
    image: docker.io/visionir/paychecks:latest
    pull_policy: always
    container_name: paychecks
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /paychecks
    volumes:
    - data:/data
    - ./src:/paychecks
    - ./pyproject.toml:/pyproject.toml
    ports:
    - 8501:8501
    environment:
    - LOG_DIR=/data
    - APP_NAME=paychecks
    - PYROSCOPE_SERVER=https://pyroscope.visionir.io
volumes :
  data:
