---
services:
  paychecks:
    image: docker.io/visionir/paychecks:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./src:/paychecks
    - ./pyproject.toml:/pyproject.toml
    ports:
    - 8501:8501
