---
services:
    paychecks:
        image: docker.io/visionir/paychecks:latest
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/paychecks/src
        ports:
            - 8501:8501
