---
services:
  data-lake:
    image: docker.io/visionir/data-lake:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./src:/data-lake
    - ./data:/data-lake/data
    - ./pyproject.toml:/data-lake/pyproject.toml
    env_file:
    - .env
