services:
  minio:
    image: minio/minio
    pull_policy: always
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001" --address=":9000"

volumes:
  minio_data:
