---
services:
  observer:
    image: python:3.11-bullseye
    container_name: observer
    working_dir: /observer
    volumes:
      - observer:/data
      - ./:/observer
    env_file:
      - .env
      - .devcontainer/devcontainer.env
    command: >
      bash -c "
      curl -sSL https://install.python-poetry.org | python3 -;
      cd /observer && poetry install;
      sleep infinity
      "
volumes:
  observer:
