---
services:
  observer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - PYPI_TOKEN=${PYPI_TOKEN}
    container_name: observer
    restart: unless-stopped
    command: [sleep, infinity]
    volumes:
    - observer:/visionir-io/data
    - ./src:/visionir-io/observer
    - ./pyproject.toml:/visionir-io/pyproject.toml
    - ./README.md:/visionir-io/README.md
    env_file:
    - .env
volumes :
  observer:
