---
apiVersion : 1

datasources:
- name: Grafana Pyroscope
  type: grafana-pyroscope-datasource
  url: https://pyroscope.visionir.io
  jsonData:
    minStep: 15s
- name: Prometheus
  type: prometheus
  access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
  url: https://prometheus.visionir.io
  jsonData:
    httpMethod: POST
    manageAlerts: true
    prometheusType: Prometheus
    prometheusVersion: 2.44.0
    cacheLevel: High
    disableRecordingRules: false
    incrementalQueryOverlapWindow: 10m
