---
services:
  cv:
    image: docker.io/visionir/cv:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./src:/cv/src
    - ./data:/cv/data
    environment:
    - AWS_ACCESS_KEY_ID=${CLOUDFLARE_R2_ACCESS_KEY_ID}
