---
name    : observer-ci-pipeline to push to PyPi
run-name: Build, Tag and Push new packge observer
on      :
  push:
    branches:
    - master
    paths:
    - apps/observer/Dockerfile
    - apps/observer/**
    - .github/workflows/observer-pypi.yml
    - '!apps/observer/.devcontainer/**'

jobs    :
  handle-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Image Directory
      id: checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          apps/observer
    - name: Generate Date
      id: date
      run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: poetry
    - uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '3.11'
    - name: build the package
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry build
    - name: publish the package
      run: |
        poetry publish
        echo "Package published to PyPi"
