---
name: observer-ci-pipeline to push to PyPi
run-name: Build, promote and Publish new packge observer
on:
  push:
    branches:
      - master
    paths:
      - apps/observer/**
      - .github/workflows/observer-pypi.yml
      - "!apps/observer/.devcontainer/**"

jobs:
  handle-pypi-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Image Directory
        id: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            apps/observer
      - name: Generate Date
        id: date
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: abatilo/actions-poetry@v2
      - name: build and publish the package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          cd apps/observer && poetry build && poetry publish
