---
name    : paychecks-ci-pipeline
run-name: Build, Tag and Push new image Paychecks
on      :
  push:
    branches:
    - master
    paths:
    - apps/paychecks/Dockerfile
    - apps/paychecks/**
    - .github/workflows/paychecks-ci.yml

jobs    :
  handle-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Image Directory
      id: checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          apps/paychecks
    - name: Generate Date
      id: date
      run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    - name: Login to Docker Hub
      id: login-docker-hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Use Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:master
          network=host
        install: true
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        file: apps/paychecks/Dockerfile
        context: apps/paychecks
        push: true
        tags: |
          ${{ secrets.DOCKER_USER }}/paychecks:${{ steps.date.outputs.TAG_DATE }}.${{ github.run_number }}
          ${{ secrets.DOCKER_USER }}/paychecks:latest
